version: "3.9"

services:
  docs-generator:
    build: .
    container_name: docs-generator
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: "mongodb://mongo:27017"
      NEXT_PUBLIC_API_URL: "http://localhost:8000"
      NEXT_PUBLIC_FRONTEND_URL: "http://localhost:8000"
      NEXT_PUBLIC_SWAGGER_URL: "http://localhost:8000/docs"
      NEXT_PUBLIC_POSTMAN_URL: "https://www.postman.com/helizium/workspace/kpi-docs-generator/collection/34916730-799b198a-2123-479d-a45d-2f7fdce7e93d"
    depends_on:
      - mongo
    volumes:
      - ./credentials.json:/app/credentials.json:ro
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000

  mongo:
      image: mongo:latest
      container_name: mongo
      ports:
        - "27017:27017"
